version: 0.0
os: linux
files:
 - source: test
   destination: /var/www/html
hooks:
 BeforeInstall:
   - location: 
     timeout: 
     runas: 
 AfterInstall:
   - location:
     timeout:
     runas:
 ApplicationStart:
   - location:
     timeout:
runas: root
